Repository Praful932/Kitabe, pull requests merged in 2021-03, with the labels that each got.

#75 Update docs with OS specific env commands
  CONTRIBUTING.md
Labels: GSSOC21, Level0

#61 Navbrand
  static/mainapp/css/layout.css
  static/mainapp/png/brand-img.png
  templates/mainapp/layout.html
Labels: GSSOC21, Level2

#83 Update contributing.md
  CONTRIBUTING.md
Labels: GSSOC21, Level0

#88 Added Top button
  static/mainapp/css/layout.css
  templates/mainapp/layout.html
Labels: GSSOC21, Level2

#102 Added home button in the nav bar
  templates/mainapp/layout.html
Labels: GSSOC21, Level1

#125 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: GSSOC21, Level0

#117 Google Authentication
  static/mainapp/css/signup.css
  templates/account/login.html
  templates/account/signup.html
Labels: GSSOC21, Level2

#120 Changed layout of explore page
  static/mainapp/css/explore.css
  templates/mainapp/explore.html
Labels: GSSOC21, Level2

#100 New feature : Library
  mainapp/helpers.py
  mainapp/tests.py
  mainapp/urls.py
  mainapp/views.py
  static/mainapp/css/read.css
  templates/mainapp/layout.html
  templates/mainapp/read.html
Labels: GSSOC21, Level3

#140 DEBUG variable in Production
  BookRecSystem/settings.py
Labels: GSSOC21, Level0

#108 Better UI for Signup and Login page
  static/mainapp/css/login.css
  static/mainapp/css/signup.css
  templates/account/login.html
  templates/account/signup.html
Labels: GSSOC21, Level2

#150 Fix bug and enhance Genre section UI
  static/mainapp/css/index.css
  templates/mainapp/index.html
Labels: GSSOC21, Level3

#153 Added search icon
  templates/mainapp/layout.html
Labels: GSSOC21, Level2

#156 Fix No. of characters shown in Book Cards
  templates/mainapp/explore.html
  templates/mainapp/genre.html
Labels: GSSOC21, Level1

#133 Added Preloader
  static/mainapp/css/index.css
  static/mainapp/png/book.svg
  templates/mainapp/index.html
Labels: GSSOC21, Level2
