Repository Praful932/Kitabe, pull requests merged in 2021-05, with the labels that each got.

#206 UI Enhancement of Login & Signup page
  static/mainapp/css/login.css
  static/mainapp/css/signup.css
  templates/account/login.html
  templates/account/signup.html
Labels: GSSOC21, Level2

#203 Added Save for Later page
  mainapp/admin.py
  mainapp/migrations/0002_saveforlater.py
  mainapp/models.py
  mainapp/tests.py
  mainapp/urls.py
  mainapp/views.py
  mainapp/views_ajax.py
  static/mainapp/css/layout.css
  templates/mainapp/layout.html
  templates/mainapp/saved_book.html
Labels: GSSOC21, Level3

#233 ⚒️[Fix]: fixed form UI
  mainapp/views.py
  static/mainapp/css/login.css
  static/mainapp/css/signup.css
  templates/account/signup.html
Labels: ui/ux

#231 Align Popular Among Us Book Cards
  static/mainapp/css/index.css
  templates/mainapp/index.html
Labels: GSSOC21, Level1

#224 Changed font of authors name across all the templates
  static/mainapp/css/explore.css
  static/mainapp/css/genre.css
  static/mainapp/css/index.css
  static/mainapp/css/read.css
  templates/mainapp/genre.html
Labels: GSSOC21, Level0

#236 Fix for button size on Explore page
  static/mainapp/css/explore.css
Labels: GSSOC21, Level0

#241 Added custom scrollbar for firefox
  static/mainapp/css/layout.css
Labels: GSSOC21, Level1

#135 Fix for when recommendations are short
  mainapp/helpers.py
  mainapp/tests.py
  mainapp/views.py
Labels: GSSOC21, Level3

#246 Modifying navbar
  static/mainapp/css/layout.css
Labels: GSSOC21, Level2

#251 Added Hovering to more details button
  static/mainapp/css/explore.css
  static/mainapp/css/genre.css
  static/mainapp/css/index.css
  static/mainapp/css/read.css
Labels: GSSOC21, Level2
